### ISSUE TITLE
Icicle reference design version

### ISSUE THREAD

**Issue by cgarlati** [polarfire-soc/apps#1]
What version of the Icicle reference design https://github.com/polarfire-soc/icicle-kit-reference-design is required for this app to work?

https://github.com/polarfire-soc/apps/blob/master/baremetal_applications/System_Services/README.md

Prerequisite #3 states "Use FlashPro Express to program the ICICLE Kit with the PolarFire SoC ICICLE Kit Reference Design job file." but doesn't specify what version  / release.

**Comment by hughbreslin** [comment]
Hi @cgarlati this app will be compatible with any version of the reference design. You should be good to use the current release and subsequent releases to test this app. I'll see about getting the readme updated to reflect this

**Comment by nitindeshpande** [comment]
Hello, 
For the latest system services and other example projects compatible with the reference design, please refer to the [polarfire-soc-bare-metal-examples](https://github.com/polarfire-soc/polarfire-soc-bare-metal-examples/tree/main/driver-examples/mss/mss-sys-services/mpfs-sys-serv-example) repo.
