### ISSUE TITLE
system_services app - Missing file mpfs-mmuart-interrupt hw all-harts debug.launch

### ISSUE THREAD

**Issue by cgarlati** [polarfire-soc/apps#2]
README.txt states "Build the project and launch the debug configuration named "mpfs-mmuart-interrupt hw all-harts debug.launch" which is configured for PolarFire SoC hardware platform."

There is no "mpfs-mmuart-interrupt hw all-harts debug.launch" file in the zip

How do we upload & run the system_services app?

**Comment by hughbreslin** [comment]
Hi @cgarlati sorry for the delay on this, yes theres a missing file here - I've attached a debug launch file configured for this project (I had to add .txt so I could attach it here). I tested this and I got a UART output debugging on my PC. This should work if you just copy it into your project folder, if it doesn't... the easiest way I think for you to add it is:
1. Open the debug configurations
2. Create a new blank debug configuration for the project
3. You will now have a .launch file in your project
4. Replace the contents of that launch file with the one I've attached here

[system_services_debug.launch.txt](https://github.com/polarfire-soc/apps/files/6516558/system_services_debug.launch.txt)

**Comment by nitindeshpande** [comment]
Hello, 
For the latest system services and other example projects, please refer to the [polarfire-soc-bare-metal-examples](https://github.com/polarfire-soc/polarfire-soc-bare-metal-examples/tree/main/driver-examples/mss/mss-sys-services/mpfs-sys-serv-example) repo.
