### ISSUE TITLE
failed to import projects into Softconsole 2021.1

### ISSUE THREAD

**Issue by frjuliano** [polarfire-soc/apps#3]
I attempted to import the zip and also import via git using softconsole and both methods failed to import any projects.

**Comment by nitindeshpande** [comment]
Hello, 
For the latest system services and other example projects, please refer to the [polarfire-soc-bare-metal-examples](https://github.com/polarfire-soc/polarfire-soc-bare-metal-examples/tree/main/driver-examples/mss/mss-sys-services/mpfs-sys-serv-example) repo.
